### ISSUE TITLE
EF Core

### ISSUE THREAD

**Issue by esamk** [orientechnologies/OrientDB.Net.Core#14]
I am not quite sure if this is the right place to talk about this, but here goes.

Did you ever consider creating EF core database provider instead of a stand-alone driver as per this discussion:

https://github.com/orientechnologies/OrientDB-NET.binary/issues/9

Being able to use OrientDb through Entity Framework would mean, IMHO, a huge boost for developer productivity. 

If you did consider the EF option at some point, could you elaborate on what made you decide against it?

**Comment by realityenigma** [comment]
Don't mind the questions at all. The current architecture does not preclude integrating into EF Core and I've actually thought about at least getting a linq provider added. Now as to why it is currently structured the way it is; simply put, we wanted to reuse as much code as possible while working towards a more modular architecture. I hope that answers your question and I never mind answering more.

**Comment by esamk** [comment]
realityenigma,

Glad to hear that. Do you accept pull requests? And if you do, do you have documentation that would allow others to think about what they might be able to contribute? For example, how do you plan to split the functionality into modules? What are the required/optional modules? What are their responsibilities/interfaces? And so on.

**Comment by realityenigma** [comment]
I will absolutely accept solid pull requests! I will take some time to develop an effective roadmap and would be open to suggestions with that as well.

**Comment by esamk** [comment]
Awesome. 
I am currently experimenting with a minimal Linq to orient dB SQL translator for querying. At this point, we're limiting ourselves to Linq-method syntax, ie. query = context.someentities.where(e => e.foo == "bar").select ... which produces an expression tree (query). Then we take the expression tree and translate it to an orient dB SQL.  

Our ExpressionTree -> SQL translation is simply an implementation of an interface method doing ExpressionTree -> string conversion. So, it could be replaced by a Gremlin translator or what have you. This code also fits well, AFAIK, to EF core provider architecture.
 
The other part of our experiment is the context and a generic IEntitySet<TEntity> for making queries. However, we don't do caching, entity proxies nor any other fancy stuff at this point. Just bare minimum.
This is not EF core compatible code (EF does these things for you).

**Comment by gar-ema** [comment]
This issue was moved to orientechnologies/OrientDB.Net#9
