### ISSUE TITLE
Question: Is still project still active/planned?

### ISSUE THREAD

**Issue by snarlynarwhal** [orientechnologies/OrientDB.Net.Core#16]
I heard about the .NET driver rewrite awhile back and came to check in on it recently and noticed the lack of activity. What's the status of it and when might we be able to expect an alpha/beta version? Any roadmap I can follow to stay updated? I found [this](https://orientdb.com/docs/2.2/Roadmap.html) but it hasn't appeared to be updated since last year and it doesn't mention this driver.

**Comment by gar-ema** [comment]
hi @snarlynarwhal. We merged all OrientDB.Net projects in one repository (https://github.com/orientechnologies/OrientDB.Net). Follow this one in order to keep updated about improvements

**Comment by snarlynarwhal** [comment]
Ahh, okay, thanks!
