### ISSUE TITLE
Feature Request: Async Queries

### ISSUE THREAD

**Issue by DavidParks8** [orientechnologies/OrientDB.Net.Core#6]
I would like to have support for async queries (using async and await with tasks).

**Comment by realityenigma** [comment]
I will investigate adding support. Thank you for the recommendation!

**Comment by alzuma** [comment]
this is doable, it all starts in "OrientDBBinaryConnectionStream.cs"

```
private void Send(byte[] buffer, NetworkStream stream)
{
	if ((stream != null) && stream.CanWrite)
	{
		try
		{
			stream.Write(buffer, 0, buffer.Length);
		}
		catch (Exception ex)
		{
			throw new Exception(ex.Message, ex.InnerException);
		}
	}
}
```
add async one
```
private async Task SendAsync(byte[] buffer, NetworkStream stream)
{
	if (stream != null && stream.CanWrite)
	{
		await stream.WriteAsync(buffer, 0, buffer.Length);
	}
}
```
and then few more places up the stream.

Need help with this?

**Comment by realityenigma** [comment]
I definitely open to help and would welcome it.

**Comment by gar-ema** [comment]
This issue was moved to orientechnologies/OrientDB.Net#12
